#! /bin/sh

##############
# WM STARTUP #
##############
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xrandr --output Virtual-1 --mode 1920x1200
pkill polybar

###########
# THEMING #
###########
. "${HOME}/.cache/wal/colors.sh"
wal -i ~/pictures/wallpapers/inferno.jpg && pywalfox update

###############
# WM SETTINGS #
###############
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	5 
bspc config window_gap		20
bspc config top_padding		40

bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


bash ~/.config/polybar/polybar.sh
